### ISSUE TITLE
Is this project supported ? 

### ISSUE THREAD

**Issue by aveerubhotla-ventana** [SystemRDL/PeakRDL-uvm#2]
Last week i tried using this project to generate uvm code using our rdl file. I ran into couple issues, for which i have opened tickets. Yesterday, i found this entire project to be deleted, and now it re-appeared (without the issues, i have reported). 
What is the plan to support this project, going forward ?

**Comment by amykyta3** [comment]
Sorry for the confusion. I had initially botched the move of this repo to the SystemRDL project, which had resulted in two copies that had diverged over time.

@zhajio1988 is the maintainer of this UVM exporter and we just recently moved his official version here (and deleted the old one). We're still working through some kinks!

If the bug you reported is still relevant to what is published in PyPi (v1.1.0), then please re-open it here as this is now the official repo for the UVM exporter.
